### ISSUE TITLE
Help Install

### ISSUE THREAD

**Issue by kevlacross** [tfohlmeister/homebridge-selve#1]
Hey. Can you help me to  install this Plugin ?

**Comment by tfohlmeister** [comment]
What exactly is your problem installing this plugin?

**Comment by tfohlmeister** [comment]
Saw your comments on https://forum.smartapfel.de/forum/thread/3505-selve-rolll%C3%A4den-ben%C3%B6tige-hilfe/. Seems to be fixed, will close this issue.
