### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by maggusf** [tfohlmeister/homebridge-selve#11]
Hi,
some typos in the readme.md (comma at the end of an array).

attached updated readme.md file (including syntax highlighting for json). not allowed to create a branch in your repo, added file instead (with ending .txt).

cheers
[README.md.txt](https://github.com/tfohlmeister/homebridge-selve/files/5583381/README.md.txt)

**Comment by tfohlmeister** [comment]
Thank you, I updated the README with your changes.
Just FYI: The normal workflow for these kind of improvements is for you to fork the project then create a branch and fix in your repository. Finally you create a MR in this repo so I can review and merge the changes.

**Comment by maggusf** [comment]
Hi,

Ok, will do that next time. ;)
