### ISSUE TITLE
Iveo Einbindung

### ISSUE THREAD

**Issue by thomadams** [tfohlmeister/homebridge-selve#12]
Hallo. 
Ich nutze Selve mittels Iveo Funksystem. Wenn ich es richtig verstehe unterstützt dieses Plugin nur commeo. 
Wäre es möglich diese Funktion  zu implementieren, falls der Aufnwand nicht allzu groß ist, mir fehlt da leider jede Kenntnis. 
Viele Grüße 
thomas

**Comment by tfohlmeister** [comment]
Der Wunsch Iveo zu unterstützen wurde hier schon häufiger an mich herangetragen.
Meine Antwort bleibt die gleiche: Die Implementierung sollte nicht sehr aufwendig sein, auch wenn aufgrund der fehlenden bi-direktionalen Kommunikation bei Iveo auf die Anzeige der aktuellen Position verzichtet werden muss.

Das große Problem für mich als Plugin-Entwickler ist, dass ich keine Iveo-Hardware besitze und daher nicht testen kann.
Wenn mir Jemand Hardware zur Verfügung stellt oder die Erweiterung selber entwickeln möchte, stehe ich aber natürlich gerne mit Rat und Tat zur Seite.
