### ISSUE TITLE
Unique device serialNumber would be great!

### ISSUE THREAD

**Issue by MarkLacey007** [tfohlmeister/homebridge-selve#17]
Hi Thorben, many thanks for this plugin, wonderful to have my roller shutters in HomeKit, great work!

Trying to import the shutters from homebridge to home assistant (to be less dependent on the big tech companies), the home assistant integration 'homekit controller' seems to only import one of my 7 shutters, because the roller shutter serialnumber field is the same for each, so the second time and subsequent times it sees the same serial number, it thinks it already has this shutter. I've seen that some other homebridge plugins have had a similar issue, which can be solved by assigning a unique serial number per shutter in the homebridge plugin, eg using something like mac address / client id as the serial number, setting this characteristic in the accessory information (homebridge-modern-forms, for example did this). 

Is it possible you could update the plugin to deal with this issue? 

Update:- I tried the following out at home, and it worked:

I edited the file 'selve-shutter-accessory.js' which on my install is in directory "/usr/local/lib/node_modules/homebridge-selve/dist", adding the last line of code below:
 // setup info service
this.informationService = new hap.Service.AccessoryInformation()
    .setCharacteristic(hap.Characteristic.Manufacturer, 'Selve')
    .setCharacteristic(hap.Characteristic.Model, 'Selve')
    .setCharacteristic(hap.Characteristic.SerialNumber, this.name);

I chose the variable 'name' because I give each shutter in my homebridge configuration at setup a name that is unique to each shutter and several characters in length. Now the shutters all show up in home assistant!

**Comment by tfohlmeister** [comment]
Hi @MarkLacey007,
thanks for the detailes request, I added your suggested changed to the latest version. Please test! :)

**Comment by MarkLacey007** [comment]
Hi @tfohlmeister!
Works perfectly for me, Homebridge/Homekit/HomeAssistant all working well. Many thanks for the speedy update!
